pub mod app_lifecycle;
pub mod clipboard;
pub mod display;
pub mod hotkey;
pub mod menu_bar;
pub mod notification;
pub mod scripting;
pub mod snapshot;
pub mod window;

pub use app_lifecycle::AppLifecyclePlugin;
pub use clipboard::ClipboardPlugin;
pub use display::DisplayPlugin;
pub use hotkey::HotkeyPlugin;
pub use menu_bar::MenuBarPlugin;
pub use notification::NotificationPlugin;
pub use scripting::ScriptingPlugin;
pub use snapshot::SnapshotPlugin;
pub use window::WindowPlugin;
